[package]
name = "roll"
version = "0.1.0"
authors = ["Alex Vermillion <dev@ajvermillion.com>"]
edition = "2018"
description = "A command line utility used to simulate dice rolls."

[dependencies]
num-bigint = { version = "0.3", features = ["rand"] }
rand = "0.7"
num-traits = "0.2"
